name: Phone Usage Tracker

on:
  repository_dispatch:
    types: [phone_unlocked_late]
  workflow_dispatch:
    inputs:
      manual_date:
        description: 'Date to add datapoint for (YYYY-MM-DD)'
        required: false
        default: ''

jobs:
  track-usage:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pytz
        
    - name: Run tracking script
      env:
        BEEMINDER_USERNAME: ${{ secrets.BEEMINDER_USERNAME }}
        BEEMINDER_AUTH_TOKEN: ${{ secrets.BEEMINDER_AUTH_TOKEN }}
        BEEMINDER_GOAL_SLUG: ${{ secrets.BEEMINDER_GOAL_SLUG }}
      run: |
        python scripts/track_phone_usage.py "${{ github.event.client_payload.date || github.event.inputs.manual_date }}"
        
    - name: Commit database changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git diff --quiet && git diff --staged --quiet || git commit -m "Update phone usage database"
        git push